### ISSUE TITLE
Create a CI workflow for creating new releases

### ISSUE THREAD

**Issue by nicomiguelino** [Screenly/Chrome-Extension#27]

**Comment by vpetersson** [comment]
So we already have the bits and pieces for it in other places. The only blocker is to remove the double compression you detected.

In short, it would look something like this:
* Using the [tag target](https://github.com/Screenly/Chrome-Extension/blob/master/.github/workflows/build.yaml#L11-L12) in the release, we can trigger a job. If you then look at the [generate SBOM](https://github.com/Screenly/Chrome-Extension/blob/master/.github/workflows/build.yaml#L64) feature, you'll notice we have a filter to make sure it only runs on tags.
* To actually generate releases, we can use the [same flow](https://github.com/Screenly/Anthias/blob/master/docs/developer-documentation.md#managing-releases) that we use for Anthias
